name: BTC 5min Update
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run analysis
        run: |
          pip install requests
          python btc_analysis.py
      - name: Commit & push btc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "BTC Auto Updater 🤖"
          git config --global user.email "actions@github.com"
          git add btc.json
          git commit -m "Auto update $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
